### ISSUE TITLE
Django2.1 不兼容

### ISSUE THREAD

**Issue by pcloth** [zwczou/weixin-python#39]
问题挺多的。
先是django_view_func方法里还在用flask的获取参数方法
我改掉后收到文本消息回复时会提示：
```sh
reply: hello too
Internal Server Error: /weixin/
Traceback (most recent call last):
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./openwx/__init__.py", line 85, in hackDjango
    return wx.django_view_func(wx,request)
  File "./openwx/__init__.py", line 81, in django_view_func
    return run(self,request)
  File "./openwx/__init__.py", line 73, in run
    content=text
TypeError: reply() got an unexpected keyword argument 'username'

```

**Comment by zwczou** [comment]
你传入的配置参数呢，reply这个有两个地方，估计用到支付(pay.py)的reply了

**Comment by zwczou** [comment]
可以参考这个 https://github.com/zwczou/weixin-python/wiki/%E5%BE%AE%E4%BF%A1%E6%B6%88%E6%81%AF 这样初始化

**Comment by pcloth** [comment]
```sh
Traceback (most recent call last):
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/zhibiyanjiusuo/zhiyansuo_beta/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./openwx/weixin/msg.py", line 263, in run
    if isinstance(text, basestring):
NameError: name 'basestring' is not defined
```

**Comment by pcloth** [comment]
@zwczou 用你那个初始化可以跑，但是前提是改掉django_view_func里面的
```python
echostr = request.args.get('echostr', '')
```
改成
```python
echostr = request.GET.get('echostr', '')
```

**Comment by zwczou** [comment]
...django view func 里面一直是request.GET你用的啥版本呀

**Comment by zwczou** [comment]
知道了，get的时候有个地方没改
