### ISSUE TITLE
msg.py中_registry属性报错

### ISSUE THREAD

**Issue by johannhuang** [zwczou/weixin-python#4]
```bash
root@42b326c392a7:/app# python manage.py
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import create_app, db
  File "/app/app/__init__.py", line 6, in <module>
    from .weixin import weixin
  File "/app/app/weixin.py", line 7, in <module>
    @weixin.all
  File "/usr/local/lib/python3.5/dist-packages/weixin/msg.py", line 196, in wrapper
    self.register(type, key, func)
  File "/usr/local/lib/python3.5/dist-packages/weixin/msg.py", line 190, in register
    self._registry.setdefault(type, dict())[key] = func
  File "/usr/local/lib/python3.5/dist-packages/weixin/msg.py", line 220, in __getattr__
    raise AttributeError('invalid attribute "' + key + '"')
AttributeError: invalid attribute "_registry"
```

**Comment by zwczou** [comment]
能提供下 manage.py 有关的部分代码么

**Comment by johannhuang** [comment]
- weixin.py

```python
from weixin import Weixin, WeixinError

weixin = Weixin()


# 监听所有没有更特殊的事件
@weixin.all
def all(**kwargs):
    print(kwargs)
    # return weixin.reply(kwargs['sender'], sender=kwargs['receiver'], content='all')
    return "hello"


# 监听所有文本消息
@weixin.text()
def hello(**kwargs):
    return dict(content="hello too!", type="text")


@weixin.text("他说")
def he_said(**kwargs):
    return weixin.reply(
        kwargs['sender'], sender=kwargs['receiver'], content='他说，他还会喜欢着你。'
    )


@weixin.text("帮助")
def world(**kwargs):
    return dict(content="目前还没有任何帮助信息，敬请期待！")


@weixin.image
def image(**kwargs):
    print(kwargs)
    return ""


@weixin.subscribe
def subscribe(**kwargs):
    print(kwargs)
    return "欢迎订阅我们的公众号"


@weixin.unsubscribe
def unsubscribe(**kwargs):
    print(kwargs)
    return ""
```

- manage.py

```python
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)

    db.init_app(app)
    bootstrap.init_app(app)

    from .weixin import weixin
    weixin.init_app(app)
    app.add_url_rule("/wxcli", view_func=weixin.view_func)

    return app
```

**Comment by zwczou** [comment]
配置文件呢？，估计是配置文件没有　WEIXIN_TOKEN　导致WeixinMsg没有初始化
